-- Ensure every curated pitch taxonomy hub (except Decro center) has a subgroup
-- room so bridges/mains like Night Street get Enter / Upload / chat.

insert into public.subgroups (name, slug, created_by)
select v.name, v.slug, 'pitch:seed'
from (values
  ('Visual Art','visual-art'),
  ('Photography','photography'),
  ('Music','music'),
  ('Film','film'),
  ('Writing','writing'),
  ('Design','design'),
  ('Craft','craft'),
  ('Games','games'),
  ('Street Photo','street-photo'),
  ('Portraiture','portraiture'),
  ('Analog Film','analog-film'),
  ('Documentary Photo','documentary-photo'),
  ('Night Photography','night-photography'),
  ('Night Street','night-street'),
  ('Oil Painting','oil-painting'),
  ('Watercolor','watercolor'),
  ('Collage','collage'),
  ('Illustration','illustration'),
  ('Street Art','street-art'),
  ('Glitch','glitch'),
  ('Generative','generative'),
  ('Electronic','electronic'),
  ('Hip Hop','hip-hop'),
  ('Ambient','ambient'),
  ('Jazz','jazz'),
  ('Score','score'),
  ('Sound Design','sound-design'),
  ('Short Film','short-film'),
  ('Experimental Film','experimental-film'),
  ('Animation','animation'),
  ('Video Art','video-art'),
  ('Documentary Film','documentary-film'),
  ('Poetry','poetry'),
  ('Fiction','fiction'),
  ('Essay','essay'),
  ('Comics','comics'),
  ('Zine','zine'),
  ('Typography','typography'),
  ('Poster Design','poster-design'),
  ('Brutalist Web','brutalist-web'),
  ('UI Specimens','ui-specimens'),
  ('3D Render','3d-render'),
  ('Ceramics','ceramics'),
  ('Textile Art','textile-art'),
  ('Sculpture','sculpture'),
  ('Woodworking','woodworking'),
  ('Video Games','video-games'),
  ('Indie Games','indie-games'),
  ('Triple-A','triple-a'),
  ('Game Art','game-art'),
  ('Pixel Art','pixel-art'),
  ('Character Design','character-design'),
  ('Album Cover','album-cover'),
  ('Music Video','music-video'),
  ('Photo Essay','photo-essay'),
  ('Fashion Film','fashion-film'),
  ('Sound Sculpture','sound-sculpture'),
  ('Game Soundtrack','game-soundtrack'),
  ('Graphic Novel','graphic-novel')
) as v(name, slug)
where not exists (select 1 from public.subgroups s where s.slug = v.slug);
